apiVersion: apps/v1
kind: Deployment
metadata:
  name: meu-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meu-app
  template:
    metadata:
      labels:
        app: meu-app
    spec:
      containers:
      - name: meu-app
        image: frontend-foodexplorer-image:latest

        imagePullPolicy: IfNotPresent  
        ports:
        - containerPort: 80
        env:
          - name: VITE_API_URL
            value: "http://localhost:5000"  # Mudança aqui!