apiVersion: apps/v1
kind: Deployment
metadata:
  name: meu-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meu-app
  template:
    metadata:
      labels:
        app: meu-app
    spec:
      containers:
      - name: meu-app
        image: my-app:tag   # Must match the loaded image!
        imagePullPolicy: IfNotPresent  # Change this!
        ports:
        - containerPort: 80
