apiVersion: v1
kind: Service
metadata:
  name: meu-app-service
spec:
  type: NodePort
  selector:
    app: meu-app  # Corrigido para corresponder ao deployment
  ports:
    - port: 3000
      targetPort: 80
      nodePort: 30007