name: CI/CD Pipeline for Kind

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

env:
  IMAGE_NAME: my-app  # Name of your Docker image
  IMAGE_TAG: tag      # Default tag for the image

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Rodar Linter
        run: |
          npm install --save-dev eslint
          npm run lint
        continue-on-error: true

      - name: Rodar Testes
        run: |
          npm install --save-dev jest
          npm run test
        continue-on-error: true

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Save Docker image as tarball
        run: |
          docker save -o my-app.tar $IMAGE_NAME:$IMAGE_TAG

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: my-app.tar

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Espera o job build terminar antes de rodar o deploydsds
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Install Kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Create Kind cluster
        run: |
          kind create cluster --name kind-clusterappfoodexplorer

      - name: Install Calico CNI
        run: |
          kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml

      - name: Wait for node to be Ready
        run: |
          timeout 300 bash -c 'while [[ $(kubectl get nodes -o jsonpath="{.items[0].status.conditions[?(@.type==\"Ready\")].status}") != "True" ]]; do sleep 5; done'
          kubectl get nodes

      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker image into Kind
        run: |
          docker load -i my-app.tar
          kind load docker-image $IMAGE_NAME:$IMAGE_TAG --name kind-clusterappfoodexplorer

      - name: Deploy to Kind cluster
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: Verify deployment
        run: |
          kubectl get pods -o wide
          kubectl get svc
